<%-- 
    Document   : homeBody
    Created on : 14-Jun-2010, 10:23:25
    Author     : Simone Spaccarotella <spa.simone@gmail.com>, Carmine Dodaro <carminedodaro@gmail.com>
--%>
<head>
    <link type="text/css" rel="stylesheet" href="resources/css/gxt-all.css">
    <link type="text/css" rel="stylesheet" href="resources/css/wsportal.css">
    <title>WS Portal Home Page</title>
</head>
<body>
    <!-- this is the autogenerated script by Ext-GWT -->
    <script type="text/javascript"  src="it.unical.inf.wsportal.WSPortal/it.unical.inf.wsportal.WSPortal.nocache.js"></script>
    <!-- this is the point where the wsportal is added in -->
    <div id="wsportal"></div>
</body>